apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  alert_rules.yml: |
    groups:
    - name: ecommerce-alerts
      rules:
      - alert: EcommerceApiDown
        expr: up{job="ecommerce-api"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "E-commerce API is down"
          description: "E-commerce API has been down for more than 5 minutes."

      - alert: HighCpuUsage
        expr: rate(container_cpu_usage_seconds_total{pod=~"ecommerce-api-.*"}[5m]) > 0.8
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 10 minutes."

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{pod=~"ecommerce-api-.*"} / container_spec_memory_limit_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 90% for more than 5 minutes."

      - alert: LowPodCount
        expr: count(kube_pod_info{pod=~"ecommerce-api-.*"}) < 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "No e-commerce API pods running"
          description: "No e-commerce API pods are currently running."